version : "3.2"

services:
  tor_socks_proxy:
    image: antiggl/tor_socks_proxy
    container_name: tor_socks_proxy
    restart: unless-stopped
    expose:
      - "9050"
    networks:
      - net-obyte-internal
  obyte_witness:
    build:
      context: ./docker
      dockerfile: Dockerfile_obyte
      #args:
      #  buildno: 1
      #  
    image: obyte-witness-node
    restart: unless-stopped
    container_name: obyte_witness
    tty: true
    entrypoint: /bin/bash
    #command : node --max-old-space-size=4096 start.js
    volumes:
      # Utilizing docker volumes
      - obyte-witness-config:/home/node/.config
      # Utilizing docker bind volume (maps to local filesystem)
      #- ${HOME}/obyte_deployment/configs/.config:/home/node/.config
    networks:
      - net-obyte-internal

networks:
  net-obyte-internal:

# Utilizing docker volumes
volumes:
  obyte-witness-config:
    external: true
