#FROM debian:buster-slim
FROM node:10

#EXPOSE 6611
#EXPOSE 80
# port to be used for email
#EXPOSE 587

RUN apt-get update &&\
	 apt-get install -y curl software-properties-common \
			sqlite3 git nano vim logrotate &&\
	mkdir -p /home/node/obyte &&\
	chown -R node:node /home/node/obyte

# ssmtp logrotate
# nodejs npm node-sqlite3\

#RUN apt-get install -y sendmail sendmailconfig

COPY ./obyte_logrotate /etc/logrotate.d/obyte

USER node

WORKDIR /home/node/obyte

RUN git clone https://github.com/byteball/headless-obyte.git 
RUN git clone https://github.com/byteball/ocore.git 
RUN git clone https://github.com/byteball/obyte-witness.git

WORKDIR /home/node/obyte/headless-obyte
RUN npm install

WORKDIR /home/node/obyte/ocore
RUN npm install

WORKDIR /home/node/obyte/obyte-witness
#RUN echo "testnet=1" > .env
RUN npm install

## Clean up a bit
RUN rm -rf /home/node/obyte/ocore &&\
	rm -rf /home/node/obyte/headless-obyte


VOLUME /home/node/.config
#RUN npm install bitcore-mnemonic

#RUN rm -r node_modules/ocore
#RUN rm -r node_modules/headless-obyte
#RUN git clone https://github.com/byteball/ocore.git ./node_modules/ocore
#RUN git clone https://github.com/byteball/headless-obyte.git ./node_modules/headless-obyyr

#COPY byteball_conf.js ./node_modules/byteballcore/conf.js

#COPY byteball_ssmtp.conf /etc/ssmtp/ssmtp.conf

CMD node --max-old-space-size=4096 start.js
